name: CI

on:
  push:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS Environment
        run: |
          chmod +x ./scripts/setAWSEnvironment.sh
          ./scripts/setAWSEnvironment.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          yarn audit --level critical --groups dependencies
          yarn install

      - name: Build Project
        run: |
          chmod +x ./scripts/setAWSEnvironment.sh
          ./scripts/setAWSEnvironment.sh
          if [[ "${{ github.ref_name }}" == "test" ]]; then
            yarn build:test
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            yarn build
          elif [[ "${{ github.ref_name }}" == "preprod" ]]; then
            yarn build:preprod
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        run: echo 'Deployment'
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set AWS Environment
      #   run: |
      #     chmod +x ./scripts/setAWSEnvironment.sh
      #     ./scripts/setAWSEnvironment.sh

      # - name: Deploy
      #   run: |
      #     if [[ "${{ github.ref_name }}" == "test" ]]; then
      #       yarn deploy:test
      #     elif [[ "${{ github.ref_name }}" == "preprod" ]]; then
      #       yarn deploy:preprod
      #     elif [[ "${{ github.ref_name }}" == "prod" ]]; then
      #       yarn deploy:prod
      #     fi
